title: The Commander's Handbook
description: Put something here later
logo: /assets/logo.png
theme: jekyll-theme-minimal

collections:
  authors:
    title: Authors
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: authors
    values:
      layout: author
