title: The Mapmaker's Guide to the Galaxy
description: A community-curated collection of Minecraft map-making tricks and tips.
logo: /assets/logo.png
theme: jekyll-theme-minimal

collections:
  authors:
    title: Authors
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: authors
    values:
      layout: author
